/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#7e747f",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#7efba4",
        "on-tertiary-fixed": "#00210c",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ebb2ff",
        "on-surface-variant": "#4d444e",
        "on-error": "#ffffff",
        "tertiary": "#003216",
        "outline-variant": "#cfc3cf",
        "surface-container": "#f4eaff",
        "on-secondary-fixed-variant": "#6c228c",
        "tertiary-container": "#004b24",
        "surface-variant": "#eaddfb",
        "on-primary-container": "#cf98e3",
        "on-primary-fixed": "#320047",
        "on-tertiary-fixed-variant": "#005228",
        "surface-container-low": "#f9f1ff",
        "tertiary-fixed-dim": "#61de8a",
        "on-secondary-fixed": "#320047",
        "primary-container": "#5b2c6f",
        "error-container": "#ffdad6",
        "secondary": "#873da6",
        "secondary-container": "#de8ffd",
        "inverse-primary": "#ebb2ff",
        "secondary-fixed": "#f8d8ff",
        "surface": "#fef7ff",
        "inverse-surface": "#342d43",
        "primary": "#431357",
        "surface-bright": "#fef7ff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f7edff",
        "surface-container-highest": "#eaddfb",
        "secondary-fixed-dim": "#ecb2ff",
        "background": "#fef7ff",
        "surface-tint": "#7c4b90",
        "on-secondary-container": "#661a86",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#efe3ff",
        "on-surface": "#1f182d",
        "error": "#ba1a1a",
        "surface-dim": "#e1d5f2",
        "primary-fixed": "#f8d8ff",
        "on-tertiary-container": "#42c372",
        "on-background": "#1f182d",
        "on-primary-fixed-variant": "#623376"
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
